package com.example.spring_app_url_shortening_service.entity;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a user role entity in the URL shortening application.
 * Defines different permission levels or access groups for users.
 *
 * <p>This entity maps to the "roles" table in the database and is used
 * to implement role-based access control in the system.</p>
 */
@Entity
@Data
@Table(name="roles")
public class Role {

    /**
     * Unique identifier for the role.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the role (e.g., "ADMIN", "USER", "MODERATOR").
     * Must be unique and non-null.
     */
    @Column(unique = true, nullable = false)
    private String roleName;
}